<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>WhoHolds.Core</RootNamespace>
    <AssemblyName>WhoHolds.Core</AssemblyName>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WhoHolds.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Constants\" />
  </ItemGroup>
</Project>
