<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>WhoHolds.Core</RootNamespace>
    <AssemblyName>WhoHolds.Core</AssemblyName>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WhoHolds.Core.Tests" />
  </ItemGroup>
</Project>
