<!-- https://devblogs.microsoft.com/nuget/introducing-central-package-management/ -->
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ModularPipelines" Version="3.2.8" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.12" />
    <PackageVersion Include="TUnit" Version="1.66.27" />
  </ItemGroup>
</Project>
