<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Using Include="Shouldly" />

    <None Update="appsettings.Testing.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WhoHolds.Pipeline\WhoHolds.Pipeline.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.Mocks" />
  </ItemGroup>
</Project>
