<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>WhoHolds.Core.Tests</RootNamespace>
    <AssemblyName>WhoHolds.Core.Tests</AssemblyName>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WhoHolds.Core\WhoHolds.Core.csproj" />
    <ProjectReference Include="..\WhoHolds.Tests.Shared\WhoHolds.Tests.Shared.csproj" />
  </ItemGroup>
</Project>
