<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>WhoHolds.Cli.Tests</RootNamespace>
    <AssemblyName>WhoHolds.Cli.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WhoHolds.Cli\WhoHolds.Cli.csproj" />
    <ProjectReference Include="..\WhoHolds.Tests.Shared\WhoHolds.Tests.Shared.csproj" />
  </ItemGroup>
</Project>
