<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Using Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WhoHolds.Cli\WhoHolds.Cli.csproj" />
    <ProjectReference Include="..\WhoHolds.Tests.Shared\WhoHolds.Tests.Shared.csproj" />
  </ItemGroup>
</Project>
